using Content.Shared._RMC.Vendors;
using Content.Client.UserInterface;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client._RMC.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntityManager _entities = default!;

    public event Action<int, int>? OnVend;
    public event Action? OnReplenishHeld;
    public event Action? OnStoreHeld;
    public event Action<int>? OnWithdrawStored;

    private SpriteSystem _sprites = default!;
    private readonly Dictionary<string, bool> _tierExpanded = new();

    public CMAutomatedVendorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprites = _entities.System<SpriteSystem>();
    }

    public void UpdateState(CMAutomatedVendorState state)
    {
        Sections.RemoveAllChildren();
        if (state.CanReplenish || state.CanStoreEquipment)
        {
            var actions = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
                Margin = new Thickness(4),
                HorizontalExpand = true,
            };

            if (state.CanReplenish)
            {
                var replenish = new Button
                {
                    Text = $"Contribute held replenishment item ({state.ReplenishmentPoints} stock points)",
                    HorizontalExpand = true,
                };
                replenish.OnPressed += _ => OnReplenishHeld?.Invoke();
                actions.AddChild(replenish);
            }

            if (state.CanStoreEquipment)
            {
                var store = new Button
                {
                    Text = $"Store your held equipment for the {state.DepartmentName}",
                    HorizontalExpand = true,
                };
                store.OnPressed += _ => OnStoreHeld?.Invoke();
                actions.AddChild(store);
            }

            Sections.AddChild(actions);
        }

        if (state.StoredItems.Count > 0)
        {
            var storedEntries = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 4,
                Margin = new Thickness(4),
                HorizontalExpand = true,
            };

            foreach (var (entry, index) in state.StoredItems.Select((value, index) => (value, index)))
                storedEntries.AddChild(CreateEntryRow(entry.Name, entry.Id, () => OnWithdrawStored?.Invoke(index)));

            var storedHeading = new CollapsibleHeading($"{state.DepartmentName} shared equipment [{state.StoredItems.Count}]")
            {
                HorizontalExpand = true,
            };
            storedHeading.Label.HorizontalExpand = true;
            storedHeading.Label.HorizontalAlignment = HAlignment.Left;
            var storedBody = new CollapsibleBody { HorizontalExpand = true, Children = { storedEntries } };
            var storedCollapsible = new Collapsible(storedHeading, storedBody)
            {
                HorizontalExpand = true,
                BodyVisible = _tierExpanded.TryGetValue($"{state.DepartmentName} shared equipment", out var expanded) ? expanded : true,
            };
            storedHeading.OnToggled += args => _tierExpanded[$"{state.DepartmentName} shared equipment"] = args.Pressed;
            Sections.AddChild(storedCollapsible);
        }

        for (var sectionIndex = 0; sectionIndex < state.Sections.Count; sectionIndex++)
        {
            var section = state.Sections[sectionIndex];
            var entries = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 4,
                Margin = new Thickness(4),
                HorizontalExpand = true,
            };

            foreach (var (entry, entryIndex) in section.Entries.Select((value, index) => (value, index)))
            {
                var text = ResolveName(entry.Name, entry.Id);
                if (entry.Amount is { } amount)
                    text += $" ({amount})";
                if (entry.Points is { } points)
                    text += $" [{points} pts]";
                if (!entry.HasAuthority)
                    text += $" — Requires {entry.RequiredAuthority}";

                var button = new Button { Text = text, HorizontalExpand = true, ToolTip = text };
                button.Disabled = entry.Amount is <= 0 ||
                                  !entry.HasAuthority ||
                                  entry.Points is { } cost && cost > state.Points ||
                                  section.Choices is { } choices && section.Purchases >= choices;
                if (!entry.HasAuthority)
                    button.ModulateSelfOverride = Color.OrangeRed;
                var capturedSection = sectionIndex;
                var capturedEntry = entryIndex;
                entries.AddChild(CreateEntryRow(text, entry.Id, () => OnVend?.Invoke(capturedSection, capturedEntry), button));
            }

            var heading = new CollapsibleHeading($"{section.Name} [{section.Entries.Count}]")
            {
                HorizontalExpand = true,
            };
            heading.Label.HorizontalExpand = true;
            heading.Label.HorizontalAlignment = HAlignment.Left;

            var body = new CollapsibleBody
            {
                HorizontalExpand = true,
                Children = { entries },
            };

            var collapsible = new Collapsible(heading, body)
            {
                HorizontalExpand = true,
                BodyVisible = _tierExpanded.TryGetValue(section.Name, out var expanded)
                    ? expanded
                    : sectionIndex == 0,
            };
            heading.OnToggled += args => _tierExpanded[section.Name] = args.Pressed;
            Sections.AddChild(collapsible);
        }
    }

    private string ResolveName(string fallback, EntProtoId id)
    {
        return _prototypes.TryIndex<EntityPrototype>(id, out var prototype) ? prototype.Name : fallback;
    }

    private Control CreateEntryRow(string text, EntProtoId id, Action onPressed, Button? button = null)
    {
        var icon = default(Texture);
        if (_prototypes.TryIndex<EntityPrototype>(id, out var prototype))
            icon = _sprites.GetPrototypeIcon(prototype).Default;

        var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        row.AddChild(new TextureRect
        {
            Texture = icon,
            SetSize = new Vector2(32, 32),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
        });

        button ??= new Button { Text = text, HorizontalExpand = true, ToolTip = text };
        button.OnPressed += _ => onPressed();
        row.AddChild(button);
        return row;
    }
}
